services:
  frontend:
    image: crocksgift/docker-project-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-fIs", "-X", "GET", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - frontend-data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    read_only: false
    security_opt:
      - no-new-privileges:true

  backend:
    image: crocksgift/docker-project-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - frontend
    networks:
      - app-network
    environment:
      - PORT=8081
    healthcheck:
      test: ["CMD", "curl", "-fIs", "-X", "GET", "http://localhost:8081/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    volumes:
      - backend-data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    read_only: false
    security_opt:
      - no-new-privileges:true

volumes:
  frontend-data:
    driver: local
  backend-data:
    driver: local

networks:
  app-network:
    driver: bridge
